// Generated by view binder compiler. Do not edit!
package com.example.alamatiko.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageButton;
import android.widget.ImageView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.alamatiko.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityHalamantitleBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final ImageView backgroundImageView;

  @NonNull
  public final ImageButton imageButton24;

  @NonNull
  public final ImageButton imageButton25;

  @NonNull
  public final ImageButton imageButton26;

  @NonNull
  public final ImageButton imageButton27;

  @NonNull
  public final ImageButton imageButton28;

  @NonNull
  public final ImageView imageView11;

  @NonNull
  public final ImageView imageView12;

  @NonNull
  public final ImageView imageView16;

  @NonNull
  public final ConstraintLayout main;

  private ActivityHalamantitleBinding(@NonNull ConstraintLayout rootView,
      @NonNull ImageView backgroundImageView, @NonNull ImageButton imageButton24,
      @NonNull ImageButton imageButton25, @NonNull ImageButton imageButton26,
      @NonNull ImageButton imageButton27, @NonNull ImageButton imageButton28,
      @NonNull ImageView imageView11, @NonNull ImageView imageView12,
      @NonNull ImageView imageView16, @NonNull ConstraintLayout main) {
    this.rootView = rootView;
    this.backgroundImageView = backgroundImageView;
    this.imageButton24 = imageButton24;
    this.imageButton25 = imageButton25;
    this.imageButton26 = imageButton26;
    this.imageButton27 = imageButton27;
    this.imageButton28 = imageButton28;
    this.imageView11 = imageView11;
    this.imageView12 = imageView12;
    this.imageView16 = imageView16;
    this.main = main;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityHalamantitleBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityHalamantitleBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_halamantitle, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityHalamantitleBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.background_image_view;
      ImageView backgroundImageView = ViewBindings.findChildViewById(rootView, id);
      if (backgroundImageView == null) {
        break missingId;
      }

      id = R.id.imageButton24;
      ImageButton imageButton24 = ViewBindings.findChildViewById(rootView, id);
      if (imageButton24 == null) {
        break missingId;
      }

      id = R.id.imageButton25;
      ImageButton imageButton25 = ViewBindings.findChildViewById(rootView, id);
      if (imageButton25 == null) {
        break missingId;
      }

      id = R.id.imageButton26;
      ImageButton imageButton26 = ViewBindings.findChildViewById(rootView, id);
      if (imageButton26 == null) {
        break missingId;
      }

      id = R.id.imageButton27;
      ImageButton imageButton27 = ViewBindings.findChildViewById(rootView, id);
      if (imageButton27 == null) {
        break missingId;
      }

      id = R.id.imageButton28;
      ImageButton imageButton28 = ViewBindings.findChildViewById(rootView, id);
      if (imageButton28 == null) {
        break missingId;
      }

      id = R.id.imageView11;
      ImageView imageView11 = ViewBindings.findChildViewById(rootView, id);
      if (imageView11 == null) {
        break missingId;
      }

      id = R.id.imageView12;
      ImageView imageView12 = ViewBindings.findChildViewById(rootView, id);
      if (imageView12 == null) {
        break missingId;
      }

      id = R.id.imageView16;
      ImageView imageView16 = ViewBindings.findChildViewById(rootView, id);
      if (imageView16 == null) {
        break missingId;
      }

      ConstraintLayout main = (ConstraintLayout) rootView;

      return new ActivityHalamantitleBinding((ConstraintLayout) rootView, backgroundImageView,
          imageButton24, imageButton25, imageButton26, imageButton27, imageButton28, imageView11,
          imageView12, imageView16, main);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
