// Generated by view binder compiler. Do not edit!
package com.example.alamatiko.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageButton;
import android.widget.ImageView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.alamatiko.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityBayaniTitleBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final ImageView backgroundImageView;

  @NonNull
  public final ImageButton imageButton39;

  @NonNull
  public final ImageButton imageButton40;

  @NonNull
  public final ImageButton imageButton41;

  @NonNull
  public final ImageButton imageButton42;

  @NonNull
  public final ImageButton imageButton43;

  @NonNull
  public final ImageView imageView11;

  @NonNull
  public final ImageView imageView13;

  @NonNull
  public final ImageView imageView15;

  @NonNull
  public final ConstraintLayout main;

  private ActivityBayaniTitleBinding(@NonNull ConstraintLayout rootView,
      @NonNull ImageView backgroundImageView, @NonNull ImageButton imageButton39,
      @NonNull ImageButton imageButton40, @NonNull ImageButton imageButton41,
      @NonNull ImageButton imageButton42, @NonNull ImageButton imageButton43,
      @NonNull ImageView imageView11, @NonNull ImageView imageView13,
      @NonNull ImageView imageView15, @NonNull ConstraintLayout main) {
    this.rootView = rootView;
    this.backgroundImageView = backgroundImageView;
    this.imageButton39 = imageButton39;
    this.imageButton40 = imageButton40;
    this.imageButton41 = imageButton41;
    this.imageButton42 = imageButton42;
    this.imageButton43 = imageButton43;
    this.imageView11 = imageView11;
    this.imageView13 = imageView13;
    this.imageView15 = imageView15;
    this.main = main;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityBayaniTitleBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityBayaniTitleBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_bayani_title, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityBayaniTitleBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.background_image_view;
      ImageView backgroundImageView = ViewBindings.findChildViewById(rootView, id);
      if (backgroundImageView == null) {
        break missingId;
      }

      id = R.id.imageButton39;
      ImageButton imageButton39 = ViewBindings.findChildViewById(rootView, id);
      if (imageButton39 == null) {
        break missingId;
      }

      id = R.id.imageButton40;
      ImageButton imageButton40 = ViewBindings.findChildViewById(rootView, id);
      if (imageButton40 == null) {
        break missingId;
      }

      id = R.id.imageButton41;
      ImageButton imageButton41 = ViewBindings.findChildViewById(rootView, id);
      if (imageButton41 == null) {
        break missingId;
      }

      id = R.id.imageButton42;
      ImageButton imageButton42 = ViewBindings.findChildViewById(rootView, id);
      if (imageButton42 == null) {
        break missingId;
      }

      id = R.id.imageButton43;
      ImageButton imageButton43 = ViewBindings.findChildViewById(rootView, id);
      if (imageButton43 == null) {
        break missingId;
      }

      id = R.id.imageView11;
      ImageView imageView11 = ViewBindings.findChildViewById(rootView, id);
      if (imageView11 == null) {
        break missingId;
      }

      id = R.id.imageView13;
      ImageView imageView13 = ViewBindings.findChildViewById(rootView, id);
      if (imageView13 == null) {
        break missingId;
      }

      id = R.id.imageView15;
      ImageView imageView15 = ViewBindings.findChildViewById(rootView, id);
      if (imageView15 == null) {
        break missingId;
      }

      ConstraintLayout main = (ConstraintLayout) rootView;

      return new ActivityBayaniTitleBinding((ConstraintLayout) rootView, backgroundImageView,
          imageButton39, imageButton40, imageButton41, imageButton42, imageButton43, imageView11,
          imageView13, imageView15, main);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
