// Generated by view binder compiler. Do not edit!
package com.example.alamatiko.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageButton;
import android.widget.ImageView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.alamatiko.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityHayopTitleBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final ImageView backgroundImageView;

  @NonNull
  public final ImageButton imageButton19;

  @NonNull
  public final ImageButton imageButton20;

  @NonNull
  public final ImageButton imageButton21;

  @NonNull
  public final ImageButton imageButton22;

  @NonNull
  public final ImageButton imageButton23;

  @NonNull
  public final ImageView imageView11;

  @NonNull
  public final ImageView imageView12;

  @NonNull
  public final ImageView imageView16;

  @NonNull
  public final ConstraintLayout main;

  private ActivityHayopTitleBinding(@NonNull ConstraintLayout rootView,
      @NonNull ImageView backgroundImageView, @NonNull ImageButton imageButton19,
      @NonNull ImageButton imageButton20, @NonNull ImageButton imageButton21,
      @NonNull ImageButton imageButton22, @NonNull ImageButton imageButton23,
      @NonNull ImageView imageView11, @NonNull ImageView imageView12,
      @NonNull ImageView imageView16, @NonNull ConstraintLayout main) {
    this.rootView = rootView;
    this.backgroundImageView = backgroundImageView;
    this.imageButton19 = imageButton19;
    this.imageButton20 = imageButton20;
    this.imageButton21 = imageButton21;
    this.imageButton22 = imageButton22;
    this.imageButton23 = imageButton23;
    this.imageView11 = imageView11;
    this.imageView12 = imageView12;
    this.imageView16 = imageView16;
    this.main = main;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityHayopTitleBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityHayopTitleBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_hayop_title, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityHayopTitleBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.background_image_view;
      ImageView backgroundImageView = ViewBindings.findChildViewById(rootView, id);
      if (backgroundImageView == null) {
        break missingId;
      }

      id = R.id.imageButton19;
      ImageButton imageButton19 = ViewBindings.findChildViewById(rootView, id);
      if (imageButton19 == null) {
        break missingId;
      }

      id = R.id.imageButton20;
      ImageButton imageButton20 = ViewBindings.findChildViewById(rootView, id);
      if (imageButton20 == null) {
        break missingId;
      }

      id = R.id.imageButton21;
      ImageButton imageButton21 = ViewBindings.findChildViewById(rootView, id);
      if (imageButton21 == null) {
        break missingId;
      }

      id = R.id.imageButton22;
      ImageButton imageButton22 = ViewBindings.findChildViewById(rootView, id);
      if (imageButton22 == null) {
        break missingId;
      }

      id = R.id.imageButton23;
      ImageButton imageButton23 = ViewBindings.findChildViewById(rootView, id);
      if (imageButton23 == null) {
        break missingId;
      }

      id = R.id.imageView11;
      ImageView imageView11 = ViewBindings.findChildViewById(rootView, id);
      if (imageView11 == null) {
        break missingId;
      }

      id = R.id.imageView12;
      ImageView imageView12 = ViewBindings.findChildViewById(rootView, id);
      if (imageView12 == null) {
        break missingId;
      }

      id = R.id.imageView16;
      ImageView imageView16 = ViewBindings.findChildViewById(rootView, id);
      if (imageView16 == null) {
        break missingId;
      }

      ConstraintLayout main = (ConstraintLayout) rootView;

      return new ActivityHayopTitleBinding((ConstraintLayout) rootView, backgroundImageView,
          imageButton19, imageButton20, imageButton21, imageButton22, imageButton23, imageView11,
          imageView12, imageView16, main);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
