// Generated by view binder compiler. Do not edit!
package com.example.alamatiko.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageButton;
import android.widget.ImageView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.alamatiko.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityPrutasGulayTitleBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final ImageView backgroundImageView;

  @NonNull
  public final ImageButton imageButton34;

  @NonNull
  public final ImageButton imageButton35;

  @NonNull
  public final ImageButton imageButton36;

  @NonNull
  public final ImageButton imageButton37;

  @NonNull
  public final ImageButton imageButton38;

  @NonNull
  public final ImageView imageView11;

  @NonNull
  public final ImageView imageView12;

  @NonNull
  public final ImageView imageView16;

  @NonNull
  public final ConstraintLayout main;

  private ActivityPrutasGulayTitleBinding(@NonNull ConstraintLayout rootView,
      @NonNull ImageView backgroundImageView, @NonNull ImageButton imageButton34,
      @NonNull ImageButton imageButton35, @NonNull ImageButton imageButton36,
      @NonNull ImageButton imageButton37, @NonNull ImageButton imageButton38,
      @NonNull ImageView imageView11, @NonNull ImageView imageView12,
      @NonNull ImageView imageView16, @NonNull ConstraintLayout main) {
    this.rootView = rootView;
    this.backgroundImageView = backgroundImageView;
    this.imageButton34 = imageButton34;
    this.imageButton35 = imageButton35;
    this.imageButton36 = imageButton36;
    this.imageButton37 = imageButton37;
    this.imageButton38 = imageButton38;
    this.imageView11 = imageView11;
    this.imageView12 = imageView12;
    this.imageView16 = imageView16;
    this.main = main;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityPrutasGulayTitleBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityPrutasGulayTitleBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_prutas_gulay_title, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityPrutasGulayTitleBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.background_image_view;
      ImageView backgroundImageView = ViewBindings.findChildViewById(rootView, id);
      if (backgroundImageView == null) {
        break missingId;
      }

      id = R.id.imageButton34;
      ImageButton imageButton34 = ViewBindings.findChildViewById(rootView, id);
      if (imageButton34 == null) {
        break missingId;
      }

      id = R.id.imageButton35;
      ImageButton imageButton35 = ViewBindings.findChildViewById(rootView, id);
      if (imageButton35 == null) {
        break missingId;
      }

      id = R.id.imageButton36;
      ImageButton imageButton36 = ViewBindings.findChildViewById(rootView, id);
      if (imageButton36 == null) {
        break missingId;
      }

      id = R.id.imageButton37;
      ImageButton imageButton37 = ViewBindings.findChildViewById(rootView, id);
      if (imageButton37 == null) {
        break missingId;
      }

      id = R.id.imageButton38;
      ImageButton imageButton38 = ViewBindings.findChildViewById(rootView, id);
      if (imageButton38 == null) {
        break missingId;
      }

      id = R.id.imageView11;
      ImageView imageView11 = ViewBindings.findChildViewById(rootView, id);
      if (imageView11 == null) {
        break missingId;
      }

      id = R.id.imageView12;
      ImageView imageView12 = ViewBindings.findChildViewById(rootView, id);
      if (imageView12 == null) {
        break missingId;
      }

      id = R.id.imageView16;
      ImageView imageView16 = ViewBindings.findChildViewById(rootView, id);
      if (imageView16 == null) {
        break missingId;
      }

      ConstraintLayout main = (ConstraintLayout) rootView;

      return new ActivityPrutasGulayTitleBinding((ConstraintLayout) rootView, backgroundImageView,
          imageButton34, imageButton35, imageButton36, imageButton37, imageButton38, imageView11,
          imageView12, imageView16, main);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
