// Generated by view binder compiler. Do not edit!
package com.example.alamatiko.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageButton;
import android.widget.ImageView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.alamatiko.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityBagayTitleBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final ImageView backgroundImageView;

  @NonNull
  public final ImageButton imageButton29;

  @NonNull
  public final ImageButton imageButton30;

  @NonNull
  public final ImageButton imageButton31;

  @NonNull
  public final ImageButton imageButton32;

  @NonNull
  public final ImageButton imageButton33;

  @NonNull
  public final ImageView imageView11;

  @NonNull
  public final ImageView imageView12;

  @NonNull
  public final ImageView imageView16;

  @NonNull
  public final ConstraintLayout main;

  private ActivityBagayTitleBinding(@NonNull ConstraintLayout rootView,
      @NonNull ImageView backgroundImageView, @NonNull ImageButton imageButton29,
      @NonNull ImageButton imageButton30, @NonNull ImageButton imageButton31,
      @NonNull ImageButton imageButton32, @NonNull ImageButton imageButton33,
      @NonNull ImageView imageView11, @NonNull ImageView imageView12,
      @NonNull ImageView imageView16, @NonNull ConstraintLayout main) {
    this.rootView = rootView;
    this.backgroundImageView = backgroundImageView;
    this.imageButton29 = imageButton29;
    this.imageButton30 = imageButton30;
    this.imageButton31 = imageButton31;
    this.imageButton32 = imageButton32;
    this.imageButton33 = imageButton33;
    this.imageView11 = imageView11;
    this.imageView12 = imageView12;
    this.imageView16 = imageView16;
    this.main = main;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityBagayTitleBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityBagayTitleBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_bagay_title, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityBagayTitleBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.background_image_view;
      ImageView backgroundImageView = ViewBindings.findChildViewById(rootView, id);
      if (backgroundImageView == null) {
        break missingId;
      }

      id = R.id.imageButton29;
      ImageButton imageButton29 = ViewBindings.findChildViewById(rootView, id);
      if (imageButton29 == null) {
        break missingId;
      }

      id = R.id.imageButton30;
      ImageButton imageButton30 = ViewBindings.findChildViewById(rootView, id);
      if (imageButton30 == null) {
        break missingId;
      }

      id = R.id.imageButton31;
      ImageButton imageButton31 = ViewBindings.findChildViewById(rootView, id);
      if (imageButton31 == null) {
        break missingId;
      }

      id = R.id.imageButton32;
      ImageButton imageButton32 = ViewBindings.findChildViewById(rootView, id);
      if (imageButton32 == null) {
        break missingId;
      }

      id = R.id.imageButton33;
      ImageButton imageButton33 = ViewBindings.findChildViewById(rootView, id);
      if (imageButton33 == null) {
        break missingId;
      }

      id = R.id.imageView11;
      ImageView imageView11 = ViewBindings.findChildViewById(rootView, id);
      if (imageView11 == null) {
        break missingId;
      }

      id = R.id.imageView12;
      ImageView imageView12 = ViewBindings.findChildViewById(rootView, id);
      if (imageView12 == null) {
        break missingId;
      }

      id = R.id.imageView16;
      ImageView imageView16 = ViewBindings.findChildViewById(rootView, id);
      if (imageView16 == null) {
        break missingId;
      }

      ConstraintLayout main = (ConstraintLayout) rootView;

      return new ActivityBagayTitleBinding((ConstraintLayout) rootView, backgroundImageView,
          imageButton29, imageButton30, imageButton31, imageButton32, imageButton33, imageView11,
          imageView12, imageView16, main);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
