// Generated by view binder compiler. Do not edit!
package com.example.alamatiko.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageButton;
import android.widget.ImageView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.alamatiko.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityPaglalabanTitleBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final ImageView backgroundImageView;

  @NonNull
  public final ImageButton imageButton49;

  @NonNull
  public final ImageButton imageButton51;

  @NonNull
  public final ImageButton imageButton52;

  @NonNull
  public final ImageButton imageButton53;

  @NonNull
  public final ImageButton imageButton54;

  @NonNull
  public final ImageView imageView11;

  @NonNull
  public final ImageView imageView13;

  @NonNull
  public final ImageView imageView15;

  @NonNull
  public final ConstraintLayout main;

  private ActivityPaglalabanTitleBinding(@NonNull ConstraintLayout rootView,
      @NonNull ImageView backgroundImageView, @NonNull ImageButton imageButton49,
      @NonNull ImageButton imageButton51, @NonNull ImageButton imageButton52,
      @NonNull ImageButton imageButton53, @NonNull ImageButton imageButton54,
      @NonNull ImageView imageView11, @NonNull ImageView imageView13,
      @NonNull ImageView imageView15, @NonNull ConstraintLayout main) {
    this.rootView = rootView;
    this.backgroundImageView = backgroundImageView;
    this.imageButton49 = imageButton49;
    this.imageButton51 = imageButton51;
    this.imageButton52 = imageButton52;
    this.imageButton53 = imageButton53;
    this.imageButton54 = imageButton54;
    this.imageView11 = imageView11;
    this.imageView13 = imageView13;
    this.imageView15 = imageView15;
    this.main = main;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityPaglalabanTitleBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityPaglalabanTitleBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_paglalaban_title, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityPaglalabanTitleBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.background_image_view;
      ImageView backgroundImageView = ViewBindings.findChildViewById(rootView, id);
      if (backgroundImageView == null) {
        break missingId;
      }

      id = R.id.imageButton49;
      ImageButton imageButton49 = ViewBindings.findChildViewById(rootView, id);
      if (imageButton49 == null) {
        break missingId;
      }

      id = R.id.imageButton51;
      ImageButton imageButton51 = ViewBindings.findChildViewById(rootView, id);
      if (imageButton51 == null) {
        break missingId;
      }

      id = R.id.imageButton52;
      ImageButton imageButton52 = ViewBindings.findChildViewById(rootView, id);
      if (imageButton52 == null) {
        break missingId;
      }

      id = R.id.imageButton53;
      ImageButton imageButton53 = ViewBindings.findChildViewById(rootView, id);
      if (imageButton53 == null) {
        break missingId;
      }

      id = R.id.imageButton54;
      ImageButton imageButton54 = ViewBindings.findChildViewById(rootView, id);
      if (imageButton54 == null) {
        break missingId;
      }

      id = R.id.imageView11;
      ImageView imageView11 = ViewBindings.findChildViewById(rootView, id);
      if (imageView11 == null) {
        break missingId;
      }

      id = R.id.imageView13;
      ImageView imageView13 = ViewBindings.findChildViewById(rootView, id);
      if (imageView13 == null) {
        break missingId;
      }

      id = R.id.imageView15;
      ImageView imageView15 = ViewBindings.findChildViewById(rootView, id);
      if (imageView15 == null) {
        break missingId;
      }

      ConstraintLayout main = (ConstraintLayout) rootView;

      return new ActivityPaglalabanTitleBinding((ConstraintLayout) rootView, backgroundImageView,
          imageButton49, imageButton51, imageButton52, imageButton53, imageButton54, imageView11,
          imageView13, imageView15, main);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
