// Generated by view binder compiler. Do not edit!
package com.example.alamatiko.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageButton;
import android.widget.ImageView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.alamatiko.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityPaniniwalaTitleBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final ImageView backgroundImageView;

  @NonNull
  public final ImageButton imageButton50;

  @NonNull
  public final ImageButton imageButton55;

  @NonNull
  public final ImageButton imageButton56;

  @NonNull
  public final ImageButton imageButton57;

  @NonNull
  public final ImageButton imageButton58;

  @NonNull
  public final ImageView imageView11;

  @NonNull
  public final ImageView imageView13;

  @NonNull
  public final ImageView imageView15;

  @NonNull
  public final ConstraintLayout main;

  private ActivityPaniniwalaTitleBinding(@NonNull ConstraintLayout rootView,
      @NonNull ImageView backgroundImageView, @NonNull ImageButton imageButton50,
      @NonNull ImageButton imageButton55, @NonNull ImageButton imageButton56,
      @NonNull ImageButton imageButton57, @NonNull ImageButton imageButton58,
      @NonNull ImageView imageView11, @NonNull ImageView imageView13,
      @NonNull ImageView imageView15, @NonNull ConstraintLayout main) {
    this.rootView = rootView;
    this.backgroundImageView = backgroundImageView;
    this.imageButton50 = imageButton50;
    this.imageButton55 = imageButton55;
    this.imageButton56 = imageButton56;
    this.imageButton57 = imageButton57;
    this.imageButton58 = imageButton58;
    this.imageView11 = imageView11;
    this.imageView13 = imageView13;
    this.imageView15 = imageView15;
    this.main = main;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityPaniniwalaTitleBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityPaniniwalaTitleBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_paniniwala_title, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityPaniniwalaTitleBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.background_image_view;
      ImageView backgroundImageView = ViewBindings.findChildViewById(rootView, id);
      if (backgroundImageView == null) {
        break missingId;
      }

      id = R.id.imageButton50;
      ImageButton imageButton50 = ViewBindings.findChildViewById(rootView, id);
      if (imageButton50 == null) {
        break missingId;
      }

      id = R.id.imageButton55;
      ImageButton imageButton55 = ViewBindings.findChildViewById(rootView, id);
      if (imageButton55 == null) {
        break missingId;
      }

      id = R.id.imageButton56;
      ImageButton imageButton56 = ViewBindings.findChildViewById(rootView, id);
      if (imageButton56 == null) {
        break missingId;
      }

      id = R.id.imageButton57;
      ImageButton imageButton57 = ViewBindings.findChildViewById(rootView, id);
      if (imageButton57 == null) {
        break missingId;
      }

      id = R.id.imageButton58;
      ImageButton imageButton58 = ViewBindings.findChildViewById(rootView, id);
      if (imageButton58 == null) {
        break missingId;
      }

      id = R.id.imageView11;
      ImageView imageView11 = ViewBindings.findChildViewById(rootView, id);
      if (imageView11 == null) {
        break missingId;
      }

      id = R.id.imageView13;
      ImageView imageView13 = ViewBindings.findChildViewById(rootView, id);
      if (imageView13 == null) {
        break missingId;
      }

      id = R.id.imageView15;
      ImageView imageView15 = ViewBindings.findChildViewById(rootView, id);
      if (imageView15 == null) {
        break missingId;
      }

      ConstraintLayout main = (ConstraintLayout) rootView;

      return new ActivityPaniniwalaTitleBinding((ConstraintLayout) rootView, backgroundImageView,
          imageButton50, imageButton55, imageButton56, imageButton57, imageButton58, imageView11,
          imageView13, imageView15, main);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
