// Generated by view binder compiler. Do not edit!
package com.example.alamatiko.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageButton;
import android.widget.ImageView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.alamatiko.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityFifthBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final ImageButton imageButton10;

  @NonNull
  public final ImageButton imageButton11;

  @NonNull
  public final ImageButton imageButton12;

  @NonNull
  public final ImageButton imageButton15;

  @NonNull
  public final ImageButton imageView10;

  @NonNull
  public final ImageView imageView2;

  @NonNull
  public final ImageView imageView5;

  @NonNull
  public final ConstraintLayout main;

  private ActivityFifthBinding(@NonNull ConstraintLayout rootView,
      @NonNull ImageButton imageButton10, @NonNull ImageButton imageButton11,
      @NonNull ImageButton imageButton12, @NonNull ImageButton imageButton15,
      @NonNull ImageButton imageView10, @NonNull ImageView imageView2,
      @NonNull ImageView imageView5, @NonNull ConstraintLayout main) {
    this.rootView = rootView;
    this.imageButton10 = imageButton10;
    this.imageButton11 = imageButton11;
    this.imageButton12 = imageButton12;
    this.imageButton15 = imageButton15;
    this.imageView10 = imageView10;
    this.imageView2 = imageView2;
    this.imageView5 = imageView5;
    this.main = main;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityFifthBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityFifthBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_fifth, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityFifthBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.imageButton10;
      ImageButton imageButton10 = ViewBindings.findChildViewById(rootView, id);
      if (imageButton10 == null) {
        break missingId;
      }

      id = R.id.imageButton11;
      ImageButton imageButton11 = ViewBindings.findChildViewById(rootView, id);
      if (imageButton11 == null) {
        break missingId;
      }

      id = R.id.imageButton12;
      ImageButton imageButton12 = ViewBindings.findChildViewById(rootView, id);
      if (imageButton12 == null) {
        break missingId;
      }

      id = R.id.imageButton15;
      ImageButton imageButton15 = ViewBindings.findChildViewById(rootView, id);
      if (imageButton15 == null) {
        break missingId;
      }

      id = R.id.imageView10;
      ImageButton imageView10 = ViewBindings.findChildViewById(rootView, id);
      if (imageView10 == null) {
        break missingId;
      }

      id = R.id.imageView2;
      ImageView imageView2 = ViewBindings.findChildViewById(rootView, id);
      if (imageView2 == null) {
        break missingId;
      }

      id = R.id.imageView5;
      ImageView imageView5 = ViewBindings.findChildViewById(rootView, id);
      if (imageView5 == null) {
        break missingId;
      }

      ConstraintLayout main = (ConstraintLayout) rootView;

      return new ActivityFifthBinding((ConstraintLayout) rootView, imageButton10, imageButton11,
          imageButton12, imageButton15, imageView10, imageView2, imageView5, main);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
