// Generated by view binder compiler. Do not edit!
package com.example.alamatiko.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageButton;
import android.widget.ImageView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.alamatiko.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityKasaysayanTitleBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final ImageView backgroundImageView;

  @NonNull
  public final ImageButton imageButton59;

  @NonNull
  public final ImageButton imageButton60;

  @NonNull
  public final ImageButton imageButton61;

  @NonNull
  public final ImageButton imageButton62;

  @NonNull
  public final ImageButton imageButton63;

  @NonNull
  public final ImageView imageView11;

  @NonNull
  public final ImageView imageView13;

  @NonNull
  public final ImageView imageView15;

  @NonNull
  public final ConstraintLayout main;

  private ActivityKasaysayanTitleBinding(@NonNull ConstraintLayout rootView,
      @NonNull ImageView backgroundImageView, @NonNull ImageButton imageButton59,
      @NonNull ImageButton imageButton60, @NonNull ImageButton imageButton61,
      @NonNull ImageButton imageButton62, @NonNull ImageButton imageButton63,
      @NonNull ImageView imageView11, @NonNull ImageView imageView13,
      @NonNull ImageView imageView15, @NonNull ConstraintLayout main) {
    this.rootView = rootView;
    this.backgroundImageView = backgroundImageView;
    this.imageButton59 = imageButton59;
    this.imageButton60 = imageButton60;
    this.imageButton61 = imageButton61;
    this.imageButton62 = imageButton62;
    this.imageButton63 = imageButton63;
    this.imageView11 = imageView11;
    this.imageView13 = imageView13;
    this.imageView15 = imageView15;
    this.main = main;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityKasaysayanTitleBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityKasaysayanTitleBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_kasaysayan_title, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityKasaysayanTitleBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.background_image_view;
      ImageView backgroundImageView = ViewBindings.findChildViewById(rootView, id);
      if (backgroundImageView == null) {
        break missingId;
      }

      id = R.id.imageButton59;
      ImageButton imageButton59 = ViewBindings.findChildViewById(rootView, id);
      if (imageButton59 == null) {
        break missingId;
      }

      id = R.id.imageButton60;
      ImageButton imageButton60 = ViewBindings.findChildViewById(rootView, id);
      if (imageButton60 == null) {
        break missingId;
      }

      id = R.id.imageButton61;
      ImageButton imageButton61 = ViewBindings.findChildViewById(rootView, id);
      if (imageButton61 == null) {
        break missingId;
      }

      id = R.id.imageButton62;
      ImageButton imageButton62 = ViewBindings.findChildViewById(rootView, id);
      if (imageButton62 == null) {
        break missingId;
      }

      id = R.id.imageButton63;
      ImageButton imageButton63 = ViewBindings.findChildViewById(rootView, id);
      if (imageButton63 == null) {
        break missingId;
      }

      id = R.id.imageView11;
      ImageView imageView11 = ViewBindings.findChildViewById(rootView, id);
      if (imageView11 == null) {
        break missingId;
      }

      id = R.id.imageView13;
      ImageView imageView13 = ViewBindings.findChildViewById(rootView, id);
      if (imageView13 == null) {
        break missingId;
      }

      id = R.id.imageView15;
      ImageView imageView15 = ViewBindings.findChildViewById(rootView, id);
      if (imageView15 == null) {
        break missingId;
      }

      ConstraintLayout main = (ConstraintLayout) rootView;

      return new ActivityKasaysayanTitleBinding((ConstraintLayout) rootView, backgroundImageView,
          imageButton59, imageButton60, imageButton61, imageButton62, imageButton63, imageView11,
          imageView13, imageView15, main);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
