// Generated by view binder compiler. Do not edit!
package com.example.alamatiko.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageButton;
import android.widget.ImageView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.alamatiko.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityPagibigTitleBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final ImageView backgroundImageView;

  @NonNull
  public final ImageButton imageButton44;

  @NonNull
  public final ImageButton imageButton45;

  @NonNull
  public final ImageButton imageButton46;

  @NonNull
  public final ImageButton imageButton47;

  @NonNull
  public final ImageButton imageButton48;

  @NonNull
  public final ImageView imageView11;

  @NonNull
  public final ImageView imageView13;

  @NonNull
  public final ImageView imageView15;

  @NonNull
  public final ConstraintLayout main;

  private ActivityPagibigTitleBinding(@NonNull ConstraintLayout rootView,
      @NonNull ImageView backgroundImageView, @NonNull ImageButton imageButton44,
      @NonNull ImageButton imageButton45, @NonNull ImageButton imageButton46,
      @NonNull ImageButton imageButton47, @NonNull ImageButton imageButton48,
      @NonNull ImageView imageView11, @NonNull ImageView imageView13,
      @NonNull ImageView imageView15, @NonNull ConstraintLayout main) {
    this.rootView = rootView;
    this.backgroundImageView = backgroundImageView;
    this.imageButton44 = imageButton44;
    this.imageButton45 = imageButton45;
    this.imageButton46 = imageButton46;
    this.imageButton47 = imageButton47;
    this.imageButton48 = imageButton48;
    this.imageView11 = imageView11;
    this.imageView13 = imageView13;
    this.imageView15 = imageView15;
    this.main = main;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityPagibigTitleBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityPagibigTitleBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_pagibig_title, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityPagibigTitleBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.background_image_view;
      ImageView backgroundImageView = ViewBindings.findChildViewById(rootView, id);
      if (backgroundImageView == null) {
        break missingId;
      }

      id = R.id.imageButton44;
      ImageButton imageButton44 = ViewBindings.findChildViewById(rootView, id);
      if (imageButton44 == null) {
        break missingId;
      }

      id = R.id.imageButton45;
      ImageButton imageButton45 = ViewBindings.findChildViewById(rootView, id);
      if (imageButton45 == null) {
        break missingId;
      }

      id = R.id.imageButton46;
      ImageButton imageButton46 = ViewBindings.findChildViewById(rootView, id);
      if (imageButton46 == null) {
        break missingId;
      }

      id = R.id.imageButton47;
      ImageButton imageButton47 = ViewBindings.findChildViewById(rootView, id);
      if (imageButton47 == null) {
        break missingId;
      }

      id = R.id.imageButton48;
      ImageButton imageButton48 = ViewBindings.findChildViewById(rootView, id);
      if (imageButton48 == null) {
        break missingId;
      }

      id = R.id.imageView11;
      ImageView imageView11 = ViewBindings.findChildViewById(rootView, id);
      if (imageView11 == null) {
        break missingId;
      }

      id = R.id.imageView13;
      ImageView imageView13 = ViewBindings.findChildViewById(rootView, id);
      if (imageView13 == null) {
        break missingId;
      }

      id = R.id.imageView15;
      ImageView imageView15 = ViewBindings.findChildViewById(rootView, id);
      if (imageView15 == null) {
        break missingId;
      }

      ConstraintLayout main = (ConstraintLayout) rootView;

      return new ActivityPagibigTitleBinding((ConstraintLayout) rootView, backgroundImageView,
          imageButton44, imageButton45, imageButton46, imageButton47, imageButton48, imageView11,
          imageView13, imageView15, main);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
