// Generated by view binder compiler. Do not edit!
package com.example.alamatiko.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageButton;
import android.widget.ImageView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.alamatiko.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class LugarTitlesBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final ImageView backgroundImageView;

  @NonNull
  public final ImageButton imageButton13;

  @NonNull
  public final ImageButton imageButton14;

  @NonNull
  public final ImageButton imageButton16;

  @NonNull
  public final ImageButton imageButton17;

  @NonNull
  public final ImageButton imageButton18;

  @NonNull
  public final ImageView imageView11;

  @NonNull
  public final ImageView imageView12;

  @NonNull
  public final ImageView imageView16;

  private LugarTitlesBinding(@NonNull ConstraintLayout rootView,
      @NonNull ImageView backgroundImageView, @NonNull ImageButton imageButton13,
      @NonNull ImageButton imageButton14, @NonNull ImageButton imageButton16,
      @NonNull ImageButton imageButton17, @NonNull ImageButton imageButton18,
      @NonNull ImageView imageView11, @NonNull ImageView imageView12,
      @NonNull ImageView imageView16) {
    this.rootView = rootView;
    this.backgroundImageView = backgroundImageView;
    this.imageButton13 = imageButton13;
    this.imageButton14 = imageButton14;
    this.imageButton16 = imageButton16;
    this.imageButton17 = imageButton17;
    this.imageButton18 = imageButton18;
    this.imageView11 = imageView11;
    this.imageView12 = imageView12;
    this.imageView16 = imageView16;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static LugarTitlesBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static LugarTitlesBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.lugar_titles, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static LugarTitlesBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.background_image_view;
      ImageView backgroundImageView = ViewBindings.findChildViewById(rootView, id);
      if (backgroundImageView == null) {
        break missingId;
      }

      id = R.id.imageButton13;
      ImageButton imageButton13 = ViewBindings.findChildViewById(rootView, id);
      if (imageButton13 == null) {
        break missingId;
      }

      id = R.id.imageButton14;
      ImageButton imageButton14 = ViewBindings.findChildViewById(rootView, id);
      if (imageButton14 == null) {
        break missingId;
      }

      id = R.id.imageButton16;
      ImageButton imageButton16 = ViewBindings.findChildViewById(rootView, id);
      if (imageButton16 == null) {
        break missingId;
      }

      id = R.id.imageButton17;
      ImageButton imageButton17 = ViewBindings.findChildViewById(rootView, id);
      if (imageButton17 == null) {
        break missingId;
      }

      id = R.id.imageButton18;
      ImageButton imageButton18 = ViewBindings.findChildViewById(rootView, id);
      if (imageButton18 == null) {
        break missingId;
      }

      id = R.id.imageView11;
      ImageView imageView11 = ViewBindings.findChildViewById(rootView, id);
      if (imageView11 == null) {
        break missingId;
      }

      id = R.id.imageView12;
      ImageView imageView12 = ViewBindings.findChildViewById(rootView, id);
      if (imageView12 == null) {
        break missingId;
      }

      id = R.id.imageView16;
      ImageView imageView16 = ViewBindings.findChildViewById(rootView, id);
      if (imageView16 == null) {
        break missingId;
      }

      return new LugarTitlesBinding((ConstraintLayout) rootView, backgroundImageView, imageButton13,
          imageButton14, imageButton16, imageButton17, imageButton18, imageView11, imageView12,
          imageView16);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
